const $=s=>document.querySelector(s), app=$('#app');
let state=JSON.parse(localStorage.getItem('siembraProto')||'null')||{role:null,view:'login',people:seed.people,available:seed.available,evals:[],pending:4,selectedPerson:null,analysisPeriods:[34,35,36],analysisMode:'all',currentWeek:36};
if(!state.currentWeek) state.currentWeek=36;
if(!state.analysisCriteria) state.analysisCriteria=[];
if(!state.reportCharts) state.reportCharts=[];
if(!state.itemReviews) state.itemReviews={};
if(!state.activeCriterion) state.activeCriterion=seed.criteria[0][0];
if(!state.defaultRecipients) state.defaultRecipients=['jefe.produccion@empresa.com','supervisor@empresa.com'];
if(!state.mailConnected) state.mailConnected=false;
if(!state.historyFailures) state.historyFailures={
  p1:[{week:36,sample:3,criterion:'c1'},{week:36,sample:8,criterion:'c10'},{week:35,sample:4,criterion:'c4'}],
  p2:[{week:36,sample:12,criterion:'c2'},{week:34,sample:7,criterion:'c5'}],
  p3:[{week:36,sample:2,criterion:'c7'},{week:36,sample:5,criterion:'c4'},{week:36,sample:7,criterion:'c9'},{week:35,sample:10,criterion:'c1'}],
  p4:[{week:36,sample:6,criterion:'c3'},{week:33,sample:9,criterion:'c10'}]
};
const save=()=>localStorage.setItem('siembraProto',JSON.stringify(state));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function modal(html){$('#modal-root').innerHTML=`<div class="modalback" onclick="if(event.target===this)closeModal()"><div class="modal">${html}</div></div>`} function closeModal(){$('#modal-root').innerHTML=''}
function layout(content,active='grupo'){return `<div class="shell"><header class="top"><div><div class="brand">Evaluación de siembra</div><div class="role">${state.role==='monitor'?'Asegurador de calidad':'Analista · prototipo'}</div></div><button class="btn ghost small" onclick="logout()">Salir</button></header>${state.role?nav(active):''}<main>${content}</main></div>`}
function nav(active){let items=state.role==='monitor'?[['grupo','Grupo'],['evaluarItems','Evaluar'],['historial','Historial']]:[['analisis','Análisis'],['gestion','Grupo'],['historial','Historial']];return `<nav class="bottom">${items.map(([v,n])=>`<button class="${active===v?'active':''}" onclick="go('${v}')">${n}</button>`).join('')}</nav>`}
function go(v){state.view=v;render()} function logout(){state.role=null;state.view='login';save();render()}
function render(){if(!state.role)return login(); if(state.view==='grupo')return group(); if(state.view==='evaluarItems')return itemEvaluation(); if(state.view==='seguimiento')return follow(); if(state.view==='nueva')return newEval(); if(state.view==='detalle')return detail(); if(state.view==='agregar')return addPerson(); if(state.view==='analisis')return analysis(); if(state.view==='tablaSemanal')return weeklyTable(); if(state.view==='correoInforme')return emailReport(); if(state.view==='resultados')return results(); if(state.view==='informe')return report(); if(state.view==='gestion')return manage(); if(state.view==='historial')return history(); if(state.view==='historialPersona')return personFailureHistory(); group()}
function login(){app.innerHTML=`<main><section class="card login"><h1>Evaluación de siembra</h1><p class="muted">Prototipo interactivo para validación del proceso.</p><label class="label">Usuario</label><input id="user" class="input" placeholder="asegurador o analista"><label class="label">Contraseña</label><input id="pass" class="input" type="password" placeholder="1234"><br><br><button class="btn primary block" onclick="doLogin()">Iniciar sesión</button><div class="demo"><b>Accesos de prueba</b><br>asegurador / 1234<br>analista / 1234</div></section></main>`}
function doLogin(){let u=$('#user').value.trim().toLowerCase(),p=$('#pass').value;if(u==='monitor')u='asegurador';if(p==='1234'&&(u==='asegurador'||u==='analista')){state.role=u==='asegurador'?'monitor':u;state.view=u==='asegurador'?'grupo':'analisis';save();render()}else toast('Credenciales de prueba incorrectas')}
function group(){let cards=state.people.map(p=>personCard(p)).join('');app.innerHTML=layout(`<section class="card hero"><div class="row between"><span class="badge">Período activo</span><button class="btn ghost small" onclick="newWeekModal()">+ Nueva semana</button></div><h2 style="margin-top:8px">Semana ${state.currentWeek}</h2><p class="muted">Período actual de evaluación</p><div class="row between"><b>${state.pending?state.pending+' pendientes de sincronización':'Todo sincronizado'}</b><button class="btn secondary" onclick="syncModal()">Sincronizar</button></div></section><button class="btn primary block" style="margin-bottom:14px" onclick="go('evaluarItems')">Evaluar grupo por ítems</button><input id="search" class="input" placeholder="Buscar sembrador..." oninput="filterPeople(this.value)"><div class="row between" style="margin:18px 0 8px"><h3 style="margin:0">Grupo · Semana ${state.currentWeek}</h3><button class="btn ghost" onclick="go('agregar')">+ Agregar</button></div><div id="people" class="grid people">${cards||'<div class="card muted">Todavía no hay sembradores en el grupo de esta semana. Use <b>+ Agregar</b> para incorporarlos.</div>'}</div>`, state.role==='analista'?'gestion':'grupo')}
function newWeekModal(){let next=state.currentWeek+1;modal(`<h3>Crear Semana ${next}</h3><p>Se cerrará la Semana ${state.currentWeek} para la demostración y se creará un grupo nuevo vacío.</p><p class="muted">Después podrá agregar los sembradores que serán evaluados en la nueva semana.</p><div class="row"><button class="btn ghost" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="createNextWeek()">Crear Semana ${next}</button></div>`)}
function createNextWeek(){state.currentWeek++;state.people=[];state.evals=[];state.pending=0;state.selectedPerson=null;state.available=seed.people.concat(seed.available).map(p=>({id:p.id+'w'+state.currentWeek,name:p.name,doc:p.doc}));save();closeModal();render();toast('Semana '+state.currentWeek+' creada. Agregue los sembradores del grupo')}
function personCard(p){let pc=Math.min(100,Math.round(p.done/p.required*100));return `<article class="card person" data-name="${p.name.toLowerCase()}" onclick="openPerson('${p.id}')"><div class="row between"><b>${p.name}</b><span class="badge ${pc<100?'warn':''}">${pc===100?'Completado':'En proceso'}</span></div><div class="row between"><span>${p.done} / ${p.required} evaluaciones</span><b>${pc}%</b></div><div class="progress"><span style="width:${pc}%"></span></div></article>`}
function filterPeople(q){document.querySelectorAll('.person').forEach(e=>e.style.display=e.dataset.name.includes(q.toLowerCase())?'':'none')}
function openPerson(id){state.selectedPerson=id;state.view='seguimiento';render()}
function current(){return state.people.find(p=>p.id===state.selectedPerson)}
function follow(){let p=current();let pc=Math.round(p.done/p.required*100);let es=state.evals.filter(e=>e.person===p.id).slice().reverse();let demo=es.length?es.map((e,i)=>`<article class="card eval" onclick="openEval('${e.id}')"><div class="row between"><b>Evaluación ${p.done-i}</b><span class="badge ${e.synced?'':'warn'}">${e.synced?'Sincronizada':'Pendiente'}</span></div><p>${e.failures.length} incumplimiento(s) · Resultado demostrativo ${e.score}%</p></article>`).join(''):`<div class="card muted">En este prototipo no se cargaron detalles de las ${p.done} evaluaciones previas. Registra una nueva para probar el flujo.</div>`;app.innerHTML=layout(`<button class="back" onclick="go('grupo')">← Volver al grupo</button><section class="card hero"><h2>${p.name}</h2><p class="muted">ID ${p.doc}</p><div class="row between"><b>Avance del seguimiento</b><strong>${p.done} / ${p.required}</strong></div><div class="progress"><span style="width:${pc}%"></span></div><p><b>${pc}% completado</b> <span class="muted">(no es desempeño)</span></p><button class="btn primary block" onclick="go('nueva')">+ Nueva evaluación</button><button class="btn ghost block" style="margin-top:8px" onclick="adjustRequired()">Ajustar evaluaciones requeridas</button></section><h3>Evaluaciones registradas en la demo</h3>${demo}`,state.role==='analista'?'gestion':'grupo')}
function newEval(){let p=current();app.innerHTML=layout(`<button class="back" onclick="confirmLeave()">← ${p.name}</button><section class="card"><span class="badge">Evaluación ${p.done+1} de ${p.required}</span><h2 style="margin-top:10px">Nueva evaluación</h2><p>${p.name}</p><h3>Criterios incumplidos</h3><p class="muted">Deje sin seleccionar los criterios que sí cumplen.</p><div class="checks">${seed.criteria.map(c=>`<label><input type="checkbox" name="crit" value="${c[0]}"> ${c[1]} ${c[2]?'<span class="badge">Crítico</span>':''}</label>`).join('')}</div><br><button class="btn primary block" onclick="saveEval()">Guardar evaluación</button></section>`,'grupo')}
function confirmLeave(){modal(`<h3>¿Salir de la evaluación?</h3><p>Los cambios sin guardar se perderán.</p><div class="row"><button class="btn ghost" onclick="closeModal()">Seguir evaluando</button><button class="btn danger" onclick="closeModal();go('seguimiento')">Descartar</button></div>`)}
function saveEval(){let ids=[...document.querySelectorAll('[name=crit]:checked')].map(x=>x.value);if(!ids.length)return modal(`<h3>Sin incumplimientos</h3><p>Todos los criterios serán considerados cumplidos.</p><div class="row"><button class="btn ghost" onclick="closeModal()">Revisar</button><button class="btn primary" onclick="closeModal();commitEval([])">Confirmar</button></div>`);commitEval(ids)}
function commitEval(ids){let p=current();p.done++;let score=Math.max(0,100-ids.length*8);state.evals.push({id:'e'+Date.now(),person:p.id,failures:ids,score,synced:false,date:new Date().toLocaleString('es-CO')});state.pending++;save();state.view='seguimiento';render();toast('Evaluación guardada localmente')}
function openEval(id){state.evalId=id;state.view='detalle';render()}
function detail(){let e=state.evals.find(x=>x.id===state.evalId),p=current();let names=e.failures.map(id=>seed.criteria.find(c=>c[0]===id)?.[1]).join(', ')||'Ninguno';app.innerHTML=layout(`<button class="back" onclick="go('seguimiento')">← Seguimiento</button><section class="card"><h2>Detalle de evaluación</h2><p><b>${p.name}</b></p><p class="muted">${e.date}</p><div class="card"><span class="muted">Resultado demostrativo</span><h1>${e.score}%</h1></div><h3>Incumplimientos</h3><p>${names}</p><p><span class="badge ${e.synced?'':'warn'}">${e.synced?'Sincronizada':'Pendiente de sincronización'}</span></p><button class="btn danger" onclick="annulEval()">Anular evaluación (demo)</button></section>`,'grupo')}
function annulEval(){modal(`<h3>Anular evaluación</h3><p>Esta acción es demostrativa y la regla real está pendiente de validación.</p><button class="btn danger" onclick="closeModal();toast('Anulación simulada')">Confirmar simulación</button>`)}
function adjustRequired(){let p=current();modal(`<h3>Ajustar evaluaciones requeridas</h3><p class="muted">Función provisional pendiente de validar permisos y reglas.</p><label class="label">Cantidad requerida</label><input id="req" class="input" type="number" min="${p.done}" value="${p.required}"><label class="label">Motivo</label><input class="input" placeholder="Ej. incapacidad"><br><br><button class="btn primary" onclick="applyRequired()">Guardar ajuste</button>`)}
function applyRequired(){let p=current(),n=Number($('#req').value);if(n<p.done)return toast('No puede ser menor a las realizadas');p.required=n;save();closeModal();render();toast('Cantidad requerida actualizada')}
function syncModal(){modal(`<h3>Sincronización</h3><p><b>${state.pending}</b> registros pendientes.</p><p class="muted">En el prototipo se simula el envío al servidor.</p><button class="btn primary block" onclick="doSync()">Sincronizar ahora</button>`)}
function doSync(){document.querySelector('.modal').innerHTML='<h3>Sincronizando...</h3><p>Simulando conexión con el servidor.</p>';setTimeout(()=>{state.evals.forEach(e=>e.synced=true);state.pending=0;save();closeModal();render();toast('Sincronización completada')},900)}
function addPerson(){app.innerHTML=layout(`<button class="back" onclick="go(state.role==='analista'?'gestion':'grupo')">← Volver</button><h2>Agregar sembrador</h2><p class="muted">Simulación de consulta a la fuente corporativa.</p><input class="input" placeholder="Buscar trabajador..." oninput="filterAvailable(this.value)"><div id="avail" style="margin-top:14px">${availableHtml()}</div>`,state.role==='analista'?'gestion':'grupo')}
function availableHtml(){return state.available.map(p=>`<article class="card available" data-name="${p.name.toLowerCase()}"><div class="row between"><div><b>${p.name}</b><div class="muted small">ID ${p.doc}</div></div><button class="btn secondary" onclick="addWorker('${p.id}')">+ Agregar</button></div></article>`).join('')||'<div class="card muted">No hay más trabajadores ficticios disponibles.</div>'}
function filterAvailable(q){document.querySelectorAll('.available').forEach(e=>e.style.display=e.dataset.name.includes(q.toLowerCase())?'':'none')}
function addWorker(id){let i=state.available.findIndex(x=>x.id===id),p=state.available.splice(i,1)[0];state.people.push({...p,required:30,done:0});save();go(state.role==='analista'?'gestion':'grupo');toast(p.name+' agregado al grupo')}
function reviewKey(){return 'w'+state.currentWeek}
function weekReviews(){let k=reviewKey();if(!state.itemReviews[k])state.itemReviews[k]={};return state.itemReviews[k]}
function itemEvaluation(){
  let reviews=weekReviews();
  if(!seed.criteria.some(c=>c[0]===state.activeCriterion))state.activeCriterion=seed.criteria[0][0];
  let c=seed.criteria.find(x=>x[0]===state.activeCriterion), review=reviews[c[0]]||null;
  let status=seed.criteria.filter(x=>reviews[x[0]]).length;
  let people=state.people.map(p=>{let checked=!review||!review.noncompliant.includes(p.id);return `<label class="worker-check"><input type="checkbox" name="workerComplies" value="${p.id}" ${checked?'checked':''}><span><b>${p.name}</b><small>ID ${p.doc}</small></span><strong>${checked?'✓':''}</strong></label>`}).join('')||'<div class="card muted">No hay sembradores en el grupo. Regrese a Grupo y agréguelos primero.</div>';
  app.innerHTML=layout(`<button class="back" onclick="go('grupo')">← Volver al grupo</button><section class="card hero"><span class="badge">Semana ${state.currentWeek}</span><h2 style="margin-top:8px">Evaluación por ítems</h2><p class="muted">Seleccione un ítem, revise a todos los sembradores y desmarque únicamente a quienes no cumplen.</p><div class="row between"><b>Ítems guardados</b><strong>${status} / ${seed.criteria.length}</strong></div><div class="progress"><span style="width:${Math.round(status/seed.criteria.length*100)}%"></span></div></section><div class="item-eval-layout"><aside class="item-menu"><h3>Ítems</h3>${seed.criteria.map(x=>`<button class="item-option ${x[0]===c[0]?'selected':''} ${reviews[x[0]]?'saved':''}" onclick="selectCriterion('${x[0]}')"><span>${x[1]}</span>${reviews[x[0]]?'<b>✓</b>':''}</button>`).join('')}</aside><section class="card item-panel"><div class="row between wrap"><div><span class="badge">Ítem seleccionado</span><h2 style="margin:8px 0 4px">${c[1]}</h2></div>${review?'<span class="badge">Guardado</span>':'<span class="badge warn">Pendiente</span>'}</div><p class="muted">Todos aparecen cumpliendo por defecto. Quite el chulo solamente a quien incumpla este ítem.</p><div class="worker-list">${people}</div><button class="btn primary block" ${state.people.length?'':'disabled'} onclick="saveCriterionReview('${c[0]}')">Guardar ${c[1]}</button></section></div>`, 'evaluarItems');
  document.querySelectorAll('[name=workerComplies]').forEach(i=>i.addEventListener('change',()=>{let strong=i.closest('.worker-check').querySelector('strong');strong.textContent=i.checked?'✓':''}));
}
function selectCriterion(id){state.activeCriterion=id;save();render()}
function saveCriterionReview(id){let noncompliant=[...document.querySelectorAll('[name=workerComplies]')].filter(x=>!x.checked).map(x=>x.value);let reviews=weekReviews();reviews[id]={noncompliant,savedAt:new Date().toLocaleString('es-CO')};state.pending++;save();render();toast('Ítem guardado localmente')}
function analysis(){
  let periods=analysisPeriodList();
  app.innerHTML=layout(`<section class="card hero"><span class="badge">Datos demostrativos</span><h2 style="margin-top:8px">Análisis de resultados</h2><p class="muted">Combine semanas e ítems libremente. Cada análisis puede agregarse al documento del informe.</p></section>
  <section class="card"><h3>1. Períodos a comparar</h3><div class="analysis-options">${periods.map(p=>`<label class="criterion"><input type="checkbox" name="period" value="${p}" ${state.analysisPeriods.includes(p)?'checked':''}> Semana ${p}</label>`).join('')}</div>
  <h3 style="margin-top:20px">2. Ítems evaluados</h3>
  <label class="criterion"><input type="radio" name="mode" value="all" ${state.analysisMode==='all'?'checked':''} onchange="toggleCriteriaPicker()"> Todos los ítems</label>
  <label class="criterion"><input type="radio" name="mode" value="critical" ${state.analysisMode==='critical'?'checked':''} onchange="toggleCriteriaPicker()"> Solo ítems críticos</label>
  <label class="criterion"><input type="radio" name="mode" value="custom" ${state.analysisMode==='custom'?'checked':''} onchange="toggleCriteriaPicker()"> Seleccionar ítems específicos</label>
  <div id="criteriaPicker" class="criteria-picker ${state.analysisMode==='custom'?'':'hidden'}"><p class="muted small">Puede seleccionar uno o varios ítems. Ejemplo: solo Manguera.</p>${seed.criteria.map(c=>`<label class="criterion"><input type="checkbox" name="analysisCrit" value="${c[0]}" ${state.analysisCriteria.includes(c[0])?'checked':''}> ${c[1]} ${c[2]?'<span class="badge">Crítico</span>':''}</label>`).join('')}</div>
  <br><button class="btn primary block" onclick="runAnalysis()">Generar gráfico comparativo</button><button class="btn secondary block" style="margin-top:9px" onclick="openWeeklyTable()">Ver tabla de conformidad de una semana</button></section>
  ${reportBasketMini()}`,'analisis')}

function openWeeklyTable(){let weeks=[...document.querySelectorAll('[name=period]:checked')].map(x=>Number(x.value));if(weeks.length!==1)return toast('Para la tabla seleccione exactamente una semana');state.tableWeek=weeks[0];state.view='tablaSemanal';save();render()}
function conformityValue(personIndex,criterionIndex,week){let n=(personIndex*7+criterionIndex*5+week*3)%18;return n<11?100:Math.max(90,100-(n-10))}
function weeklyTable(){let week=state.tableWeek||state.currentWeek;let people=state.people.length?state.people:seed.people;let cols=[['c7','Aseo sitio de trabajo'],['c2','Densidad y distribución'],['c3','Estado de la planta'],['c1','Planta inclinada'],['c4','Profundidad de la planta'],['c5','Selección de esquejes'],['c9','Siembra con marcador'],['c10','Conteo de líneas'],['c10','Ubicación mangueras']];let rows=people.map((p,pi)=>{let vals=cols.map((c,ci)=>conformityValue(pi,ci,week));let total=Math.round(vals.reduce((a,b)=>a+b,0)/vals.length);return `<tr><td class="namecell">${p.name}</td>${vals.map(v=>`<td>${v}%</td>`).join('')}<td><b>${total}%</b></td></tr>`}).join('');let weekly=[week-3,week-2,week-1,week].filter(w=>w>0).map((w,i)=>[w,91+((w*5+i*2)%7)]);let mini=weekly.map(x=>`<tr><td>SEMANA ${x[0]}</td><td>${x[1]}%</td></tr>`).join('');let bars=weekly.map(x=>`<div class="print-bar-item"><b>${x[1]}%</b><div class="print-bar" style="height:${Math.max(25,x[1]-55)*3}px"></div><span>SEMANA ${x[0]}</span></div>`).join('');app.innerHTML=layout(`<div class="no-print"><button class="back" onclick="go('analisis')">← Volver a análisis</button><div class="row between wrap"><div><h2>Conformidad individual · Semana ${week}</h2><p class="muted">Vista previa del formato semanal solicitado.</p></div><div class="row wrap"><button class="btn secondary" onclick="openEmailReport()">✉ Enviar por correo</button><button class="btn primary" onclick="window.print()">🖨 Imprimir</button></div></div></div><section class="report-sheet"><div class="report-head"><div><b>JARDINES DE SAN NICOLÁS S.A.S.</b></div><div><b>RUTA DE APRENDIZAJE</b></div><div class="assurance"><b>ASEGURAMIENTO</b></div><div>INDICADOR</div><div>METEORO</div><div></div><div>ÁREA</div><div>SIEMBRA EN CAMPO</div><div></div><div>RESPONSABLE</div><div>ERASMO GOMEZ</div><div></div></div><h3 class="table-title">RESULTADOS CONFORMIDAD INDIVIDUAL SEMANA ${week}</h3><div class="table-scroll"><table class="conformity-table"><thead><tr><th>NOMBRE DEL COLABORADOR</th>${cols.map(c=>`<th>${c[1]}</th>`).join('')}<th>Conformidad Total</th></tr></thead><tbody>${rows}</tbody></table></div><div class="weekly-summary"><table class="mini-table"><thead><tr><th>SEMANAS</th><th>CONFORMIDAD GRUPAL</th></tr></thead><tbody>${mini}</tbody></table><div class="print-chart"><h3>METEORO · CONFORMIDAD GRUPAL (SEMANAL)</h3><div class="print-bars">${bars}</div></div></div><div class="signature-grid"><div>JEFE PRODUCCIÓN</div><div>SUPERVISOR (J)</div><div>SUPERVISOR (M)</div><div>JEFE SAVIA - METEORO</div></div></section><div class="no-print action-stack"><button class="btn secondary block" onclick="openEmailReport()">✉ Enviar tabla en PDF por correo</button><button class="btn primary block" onclick="window.print()">🖨 Mandar a imprimir</button></div>`,'analisis')}
function analysisPeriodList(){let max=Math.max(state.currentWeek,38,...seed.periods.map(p=>p.id));let min=Math.max(1,max-5);return Array.from({length:max-min+1},(_,i)=>min+i)}
function toggleCriteriaPicker(){let mode=document.querySelector('[name=mode]:checked')?.value;let el=$('#criteriaPicker');if(el)el.classList.toggle('hidden',mode!=='custom')}
function runAnalysis(){state.analysisPeriods=[...document.querySelectorAll('[name=period]:checked')].map(x=>Number(x.value)).sort((a,b)=>a-b);state.analysisMode=document.querySelector('[name=mode]:checked').value;state.analysisCriteria=[...document.querySelectorAll('[name=analysisCrit]:checked')].map(x=>x.value);if(!state.analysisPeriods.length)return toast('Seleccione al menos un período');if(state.analysisMode==='custom'&&!state.analysisCriteria.length)return toast('Seleccione al menos un ítem');state.view='resultados';save();render()}
function selectedCriteria(){if(state.analysisMode==='critical')return seed.criteria.filter(c=>c[2]);if(state.analysisMode==='custom')return seed.criteria.filter(c=>state.analysisCriteria.includes(c[0]));return seed.criteria}
function demoValue(criterionIndex,week){return Math.max(2,Math.min(24,5+((criterionIndex*4+week*3)%15)))}
function modeLabel(){if(state.analysisMode==='critical')return 'Ítems críticos';if(state.analysisMode==='custom')return selectedCriteria().map(c=>c[1]).join(', ');return 'Todos los ítems'}
function results(){let criteria=selectedCriteria(), periods=state.analysisPeriods;let legend=periods.map(w=>`<span class="legend-item"><i class="week-swatch swatch-${w%6}"></i>Semana ${w}</span>`).join('');let chart=criteria.map(c=>{let idx=seed.criteria.findIndex(x=>x[0]===c[0]);return `<div class="compare-row"><div class="compare-label">${c[1]}</div><div class="week-bars">${periods.map(w=>{let v=demoValue(idx,w);return `<div class="week-bar-line"><span class="week-name">S${w}</span><div class="bar"><span class="week-fill fill-${w%6}" style="width:${v*4}%"></span></div><b>${v}%</b></div>`}).join('')}</div></div>`}).join('');
  app.innerHTML=layout(`<button class="back" onclick="go('analisis')">← Modificar análisis</button><div class="row between wrap"><div><h2 style="margin-bottom:5px">Resultado comparativo</h2><p class="muted">Semanas ${periods.join(', ')} · ${modeLabel()} · valores ficticios</p></div><span class="badge">${criteria.length} ítem(s)</span></div>
  <section class="card"><h3>Incumplimientos por ítem y semana</h3><div class="legend">${legend}</div><p class="muted small">Cada semana se muestra por separado para facilitar la comparación.</p>${chart}</section>
  <div class="action-stack"><button class="btn secondary block" onclick="addCurrentChartToReport()">+ Agregar este gráfico al informe</button><button class="btn ghost block" onclick="go('analisis')">Crear otro análisis</button><button class="btn primary block" onclick="go('informe')">Ver documento del informe (${state.reportCharts.length})</button></div>`,'analisis')}
function addCurrentChartToReport(){let item={id:'g'+Date.now(),periods:[...state.analysisPeriods],mode:state.analysisMode,criteria:selectedCriteria().map(c=>c[0]),title:chartDefaultTitle()};state.reportCharts.push(item);save();render();toast('Gráfico agregado al documento')}
function chartDefaultTitle(){return `${modeLabel()} · Semanas ${state.analysisPeriods.join(', ')}`}
function reportBasketMini(){if(!state.reportCharts.length)return `<section class="card"><h3>Documento del informe</h3><p class="muted">Todavía no ha agregado gráficos. Genere un análisis y agréguelo cuando le resulte útil.</p></section>`;return `<section class="card"><div class="row between"><h3 style="margin:0">Documento del informe</h3><span class="badge">${state.reportCharts.length} gráfico(s)</span></div><p class="muted small">Los gráficos agregados se conservan mientras continúa analizando.</p><button class="btn ghost block" onclick="go('informe')">Revisar documento</button></section>`}
function reportChartHtml(g,i){let criteria=seed.criteria.filter(c=>g.criteria.includes(c[0]));let legend=g.periods.map(w=>`<span class="legend-item"><i class="week-swatch swatch-${w%6}"></i>Semana ${w}</span>`).join('');let chart=criteria.map(c=>{let idx=seed.criteria.findIndex(x=>x[0]===c[0]);return `<div class="compare-row compact"><div class="compare-label">${c[1]}</div><div class="week-bars">${g.periods.map(w=>{let v=demoValue(idx,w);return `<div class="week-bar-line"><span class="week-name">S${w}</span><div class="bar"><span class="week-fill fill-${w%6}" style="width:${v*4}%"></span></div><b>${v}%</b></div>`}).join('')}</div></div>`}).join('');return `<article class="card report-chart"><div class="row between wrap"><div><span class="badge">Gráfico ${i+1}</span><h3>${g.title}</h3></div><button class="btn danger small" onclick="removeReportChart('${g.id}')">Quitar</button></div><div class="legend">${legend}</div>${chart}<label class="label">Conclusión / nota del analista</label><textarea class="input report-note" rows="3" placeholder="Escriba aquí una conclusión para este gráfico..." oninput="saveReportNote('${g.id}',this.value)">${g.note||''}</textarea></article>`}
function report(){let body=state.reportCharts.length?state.reportCharts.map(reportChartHtml).join(''):`<div class="card muted">Aún no hay gráficos en el documento. Vuelva a Análisis, genere un gráfico y pulse <b>Agregar este gráfico al informe</b>.</div>`;app.innerHTML=layout(`<button class="back" onclick="go('analisis')">← Seguir analizando</button><section class="card hero"><span class="badge">Documento en construcción</span><h2 style="margin-top:8px">Informe de resultados</h2><p class="muted">Agregue tantos análisis como necesite antes de generar el informe final.</p><div class="row between"><b>Gráficos agregados</b><strong>${state.reportCharts.length}</strong></div></section>${body}<button class="btn primary block" ${state.reportCharts.length?'':'disabled'} onclick="fakeReport()">Generar informe con ${state.reportCharts.length} gráfico(s)</button><div id="reportStatus"></div>`,'analisis')}
function removeReportChart(id){state.reportCharts=state.reportCharts.filter(g=>g.id!==id);save();render();toast('Gráfico retirado del documento')}
function saveReportNote(id,note){let g=state.reportCharts.find(x=>x.id===id);if(g){g.note=note;save()}}
function fakeReport(){if(!state.reportCharts.length)return toast('Agregue al menos un gráfico');$('#reportStatus').innerHTML='<p class="card">Generando documento...</p>';setTimeout(()=>$('#reportStatus').innerHTML='<div class="card"><span class="badge">✓ Informe generado</span><p class="muted" style="margin-top:10px">Simulación: el informe final contendría los '+state.reportCharts.length+' gráficos seleccionados y las notas del analista.</p></div>',800)}
function manage(){group()}
function history(){
  let week=state.currentWeek;
  let people=state.people.length?state.people:seed.people;
  let withFailures=people.filter(p=>(state.historyFailures[p.id]||[]).some(f=>f.week===week));
  let cards=withFailures.map(p=>{
    let n=(state.historyFailures[p.id]||[]).filter(f=>f.week===week).length;
    return `<article class="card person history-person" onclick="openFailureHistory('${p.id}')"><div class="row between"><div><b>${p.name}</b><div class="muted">${p.doc?'ID '+p.doc:''}</div></div><span class="badge warn">${n} fallo${n===1?'':'s'}</span></div><p class="muted small" style="margin-bottom:0">Tocar para consultar el historial de fallos →</p></article>`
  }).join('');
  app.innerHTML=layout(`<section class="card hero"><span class="badge">Última semana evaluada</span><h2 style="margin:8px 0 4px">Fallos · Semana ${week}</h2><p class="muted">Se muestran únicamente los sembradores que presentaron al menos un incumplimiento durante la última semana evaluada.</p><div class="row between"><b>Sembradores con fallos</b><strong>${withFailures.length}</strong></div></section><h3>Personas con fallos</h3>${cards||'<div class="card muted">No se registraron fallos en la última semana evaluada.</div>'}<section class="card"><h3>Consulta histórica</h3><p class="muted small">Seleccione una persona para ver qué ítem incumplió, en qué semana ocurrió y en qué muestra fue registrado.</p></section>`, 'historial')
}
function openFailureHistory(id){state.historyPerson=id;state.view='historialPersona';save();render()}
function personFailureHistory(){
  let people=[...seed.people,...seed.available,...state.people];
  let p=people.find(x=>x.id===state.historyPerson)||seed.people.find(x=>x.id===state.historyPerson);
  if(!p){state.view='historial';return render()}
  let failures=(state.historyFailures[p.id]||[]).slice().sort((a,b)=>b.week-a.week||b.sample-a.sample);
  let rows=failures.map(f=>{let c=seed.criteria.find(x=>x[0]===f.criterion);return `<tr><td><b>${c?c[1]:f.criterion}</b></td><td>Semana ${f.week}</td><td>Muestra ${f.sample}</td></tr>`}).join('');
  app.innerHTML=layout(`<button class="back" onclick="go('historial')">← Volver al historial</button><section class="card hero"><span class="badge warn">Historial de fallos</span><h2 style="margin:8px 0 4px">${p.name}</h2><p class="muted">${p.doc?'ID '+p.doc+' · ':''}${failures.length} fallo(s) registrados en la demostración</p></section><section class="card"><h3>Detalle de incumplimientos</h3><p class="muted">Cada fila indica el ítem que falló y el momento exacto del seguimiento en que se registró.</p><div class="table-scroll"><table class="failure-table"><thead><tr><th>Ítem incumplido</th><th>Semana</th><th>Muestra</th></tr></thead><tbody>${rows||'<tr><td colspan="3">Sin fallos registrados.</td></tr>'}</tbody></table></div></section>`, 'historial')
}

function openEmailReport(){state.view='correoInforme';save();render()}
function connectMail(){state.mailConnected=true;save();render();toast('Cuenta conectada para la demostración')}
function disconnectMail(){state.mailConnected=false;save();render()}
function emailReport(){let week=state.tableWeek||state.currentWeek;if(!state.mailConnected){app.innerHTML=layout(`<button class="back" onclick="go('tablaSemanal')">← Volver a la tabla</button><section class="card hero"><span class="badge">Envío seguro</span><h2 style="margin-top:8px">Enviar informe · Semana ${week}</h2><p class="muted">En la aplicación real se utilizará el inicio de sesión seguro del proveedor de correo. La aplicación no almacenará ni conocerá la contraseña.</p></section><section class="card mail-connect"><h3>Conectar cuenta de correo</h3><label class="label">Correo corporativo</label><input id="mailAccount" class="input" type="email" placeholder="nombre@empresa.com" value="analista@empresa.com"><p class="muted small">Prototipo: el botón siguiente simula la autorización externa (OAuth). No escriba una contraseña real.</p><button class="btn primary block" onclick="connectMail()">Conectar con correo corporativo</button></section>`,'analisis');return}
let recipients=state.defaultRecipients.map((e,i)=>`<div class="recipient"><span>✉ ${e}</span><span class="badge">Predeterminado</span><button class="btn ghost small" onclick="removeDefaultRecipient(${i})">Quitar</button></div>`).join('');app.innerHTML=layout(`<button class="back" onclick="go('tablaSemanal')">← Volver a la tabla</button><section class="card hero"><div class="row between wrap"><div><span class="badge">Cuenta conectada</span><h2 style="margin:8px 0 4px">Enviar informe · Semana ${week}</h2><p class="muted">analista@empresa.com</p></div><button class="btn ghost small" onclick="disconnectMail()">Cambiar cuenta</button></div></section><section class="card"><h3>Destinatarios</h3><p class="muted">Los predeterminados aparecen automáticamente en cada envío.</p><div id="recipientList">${recipients}</div><div id="tempRecipients"></div><div class="recipient-add"><input id="newRecipient" class="input" type="email" placeholder="otro.correo@empresa.com"><button class="btn secondary" onclick="addRecipient(false)">Agregar</button></div><label class="save-default"><input id="saveDefault" type="checkbox"> Agregar a destinatarios predeterminados</label></section><section class="card"><label class="label">Asunto</label><input id="mailSubject" class="input" value="Resultados de conformidad de siembra - Semana ${week}"><label class="label">Cuerpo del correo</label><textarea id="mailBody" class="input mail-body">Buenos días,\n\nAdjunto se envía el informe de resultados de conformidad correspondiente a la Semana ${week}.\n\nCordialmente.</textarea><div class="attachment"><div class="pdf-icon">PDF</div><div><b>Resultados_Conformidad_Semana_${week}.pdf</b><small>Tabla semanal de conformidad · PDF generado por la aplicación</small></div></div><button class="btn primary block" onclick="sendDemoEmail()">Enviar correo</button></section>`,'analisis')}
function addRecipient(){let inp=$('#newRecipient'),email=inp.value.trim();if(!email||!email.includes('@'))return toast('Escriba un correo válido');if($('#saveDefault').checked){if(!state.defaultRecipients.includes(email))state.defaultRecipients.push(email);save();render();toast('Agregado a predeterminados')}else{let box=$('#tempRecipients'),d=document.createElement('div');d.className='recipient temp';d.innerHTML=`<span>✉ ${email}</span><span class="badge warn">Solo este envío</span><button class="btn ghost small" onclick="this.parentElement.remove()">Quitar</button>`;box.appendChild(d);inp.value='';toast('Agregado al envío actual')}}
function removeDefaultRecipient(i){state.defaultRecipients.splice(i,1);save();render()}
function sendDemoEmail(){let subject=$('#mailSubject').value.trim();if(!subject)return toast('El asunto no puede estar vacío');modal(`<h3>Correo enviado (simulación)</h3><p>El prototipo simuló el envío del informe de la <b>Semana ${state.tableWeek||state.currentWeek}</b> en formato PDF.</p><p class="muted">En la aplicación real, el backend generará el PDF y lo enviará mediante el proveedor de correo autorizado.</p><button class="btn primary block" onclick="closeModal()">Aceptar</button>`)}

render();
